[project]
name = "advent-of-code"
version = "0.1.0"
description = "Solutions to the Advent of Code challenges"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []


[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.8.1",
]